#!/bin/bash

echo "🚀 CampusCare - Sistem Pelaporan Kerusakan Fasilitas Kampus"
echo "==========================================================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}📋 Setup Instructions:${NC}"
echo ""
echo -e "${BLUE}1. BACKEND SETUP${NC}"
echo "   cd backend"
echo "   npm install"
echo "   npm run dev"
echo ""
echo -e "${BLUE}2. FRONTEND SETUP (di terminal baru)${NC}"
echo "   cd frontend"
echo "   npm install"
echo "   npm run dev"
echo ""
echo -e "${GREEN}✅ Default Admin Account:${NC}"
echo "   Email: admin@campuscare.com"
echo "   Password: admin123"
echo ""
echo -e "${BLUE}📍 URLs:${NC}"
echo "   Frontend: http://localhost:3000"
echo "   Backend API: http://localhost:5000/api"
echo ""
echo -e "${YELLOW}📌 API Endpoints:${NC}"
echo ""
echo "Auth:"
echo "  POST   /api/auth/register"
echo "  POST   /api/auth/login"
echo "  GET    /api/auth/profile"
echo ""
echo "Reports (Pelapor):"
echo "  POST   /api/reports/create"
echo "  GET    /api/reports/my-reports"
echo "  GET    /api/reports/:id"
echo "  PUT    /api/reports/:id"
echo ""
echo "Reports (Admin):"
echo "  GET    /api/reports"
echo "  PUT    /api/reports/:id/status"
echo "  GET    /api/reports/statistics/all"
echo ""
echo "Users (Admin):"
echo "  GET    /api/users"
echo "  PUT    /api/users/:id"
echo "  DELETE /api/users/:id"
echo ""
